github.com:
    users:
        theramencode:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: theramencode
